micronaut:
  application:
    name: pizzaservice

mongodb.uri: mongodb://user:password@${MONGO_HOST:pizzadb}:${MONGO_PORT:27017}/test
db:
  name: 'test'
  collection: 'pizza'
netty:
  default:
    allocator:
      max-order: 3
